[package]
name = "bls_eth_rust"
version = "0.0.2"
authors = ["MITSUNARI Shigeo <herumi@nifty.com>"]
edition = "2018"

[[bench]]
name = "bls381_benches"
harness = false

[dependencies]
criterion = "0.3.0"
hex = "0.4.0"
